version: '3.1'
services:
  stats-server:
    build: stat_service
    container_name: stat_service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shanya482@
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: postgresql_stats
    ports:
        - "6545:5432"
    volumes:
        - /var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=stat_service
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Shanya482@

  ewm-service:
    build: main_service
    container_name: main_service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shanya482@
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - SERVER_URL=http://stats-server:9090


  ewm-db:
    image: postgres:14-alpine
    container_name: postgresql_ewm
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shanya482@
